'use client';

import { useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { contentService } from '@/lib/contentService';

export default function ContentImporter() {
    const { data: session, status } = useSession();
    const router = useRouter();
    const [jsonInput, setJsonInput] = useState('');
    const [loading, setLoading] = useState(false);
    const [message, setMessage] = useState({ type: '', text: '' });

    if (status === 'loading') return <div className="p-8">Verifying access...</div>;
    if (!session || (session.user as any).role !== 'faculty') {
        return <div className="p-8 text-red-600">Access Denied. Faculty only.</div>;
    }

    const handleImport = async () => {
        try {
            setLoading(true);
            setMessage({ type: '', text: '' });
            const data = JSON.parse(jsonInput);

            if (!data.chapter || !data.topics) {
                throw new Error('Invalid JSON structure. Needs "chapter" and "topics" array.');
            }

            await contentService.importChapter(data);
            setMessage({ type: 'success', text: `Successfully imported "${data.chapter}" with ${data.topics.length} topics!` });
            setJsonInput('');
        } catch (err: any) {
            setMessage({ type: 'error', text: err.message });
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 p-8">
            <div className="max-w-4xl mx-auto">
                <div className="bg-white rounded-2xl shadow-xl p-8">
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">Smart Content Importer</h1>
                    <p className="text-gray-600 mb-8">Paste the JSON generated by ChatGPT here to create a new Chapter and all its Topics instantly.</p>

                    <textarea
                        className="w-full h-96 p-4 font-mono text-sm border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all"
                        placeholder='{ "chapter": "...", "description": "...", "topics": [...] }'
                        value={jsonInput}
                        onChange={(e) => setJsonInput(e.target.value)}
                    />

                    {message.text && (
                        <div className={`mt-4 p-4 rounded-lg flex items-center ${message.type === 'success' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>
                            {message.type === 'success' ? (
                                <svg className="w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg>
                            ) : (
                                <svg className="w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" /></svg>
                            )}
                            {message.text}
                        </div>
                    )}

                    <div className="mt-8 flex justify-end items-center space-x-4">
                        <button
                            onClick={() => router.push('/faculty')}
                            className="px-6 py-3 text-gray-600 font-semibold hover:text-gray-900 transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={handleImport}
                            disabled={loading || !jsonInput}
                            className={`px-8 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-bold rounded-xl shadow-lg hover:shadow-xl transform hover:scale-105 transition-all flex items-center ${loading ? 'opacity-50 cursor-not-allowed' : ''}`}
                        >
                            {loading && <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-3"></div>}
                            {loading ? 'Importing...' : 'Start Import'}
                        </button>
                    </div>
                </div>

                <div className="mt-12 bg-indigo-50 rounded-2xl p-8 border border-indigo-100">
                    <h3 className="text-lg font-bold text-indigo-900 mb-4">Pro Tip: Structure for ChatGPT</h3>
                    <p className="text-indigo-800 text-sm leading-relaxed">
                        When asking ChatGPT to generate content, use this prompt:
                        <br /><br />
                        <code className="block bg-white p-4 rounded-lg border border-indigo-200">
                            "Generate Chapter X for my Digital Transformation course in JSON format with 'chapter', 'description',
                            and an array of 'topics' where each topic has 'title' and 'content' (Markdown supported)."
                        </code>
                    </p>
                </div>
            </div>
        </div>
    );
}
